In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
def numerical_diff(f, x):
    h = 1e-4
    return (f(x+h) - f(x-h))/(2*h)

In [3]:
def funtion_l(x):
    return 0.01*x**2 + 0.1*x

In [4]:
numerical_diff(funtion_l, 5)

0.1999999999990898

In [5]:
def function_2(x):
    return np.sum(x**2)

In [6]:
def numerical_gradient(f, x):
    h = 1e-4
    grad = np.zeros_like(x)
    
    for idx in range(x.size):
        tmp_val = x[idx]
        x[idx] = tmp_val + h
        fxh1 = f(x)
        
        x[idx] = tmp_val - h
        fxh2 = f(x)
        
        grad[idx] = (fxh1 - fxh2) / (2*h)
        x[idx] = tmp_val
        
    return grad

In [7]:
numerical_gradient(function_2, np.array([3., 4.]))

array([6., 8.])

In [8]:
numerical_gradient(function_2, np.array([3, 4]))

array([25000, 35000])

why?

In [9]:
np.array([3, 4])

array([3, 4])

In [10]:
np.array([3., 4.])

array([3., 4.])

In [11]:
def gradient_descent(f, init_x, lr=0.01, step_num=100):
    x = init_x
    
    for i in range(step_num):
        grad = numerical_gradient(f, x)
        x -= lr*grad
        
    return x

In [12]:
init_x = np.array([-3., 4.])
gradient_descent(function_2, init_x, lr=0.1, step_num=100)

array([-6.11110793e-10,  8.14814391e-10])